name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set env to staging
      if: endsWith(github.ref, '/master')
      run: |
        base64 --decode <<< $ENVSETUP | sh
      env:
        ENVSETUP: ${{ secrets.ENVSETUP_STAGING }}
    - name: Set env to production
      if: endsWith(github.ref, '/production')
      run: |
        base64 --decode <<< $ENVSETUP | sh
      env:
        ENVSETUP: ${{ secrets.ENVSETUP_PRODUCTION }}
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup Node.js
      uses: actions/setup-node@v1
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install dependencies
      run: |
        yarn
    - name: Build
      run: |
        yarn build
    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: build
    - name: Copy gcloud config
      run: |
        cp gcloud/$GCLOUD_CONFIG gcloud/app.yaml
    - name: Archive gcloud config
      uses: actions/upload-artifact@v1
      with:
        name: gcloud
        path: gcloud
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Setup Cloud SDK
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
         version: '270.0.0'
         service_account_key: ${{ secrets.GCLOUD_KEY }}
    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: dist
    - name: Download gcloud config
      uses: actions/download-artifact@v1
      with:
        name: gcloud
        path: .
    - name: Deploy to GAE
      run: |
        gcloud app deploy app.yaml --project=$GCLOUD_PROJECT
      env:
        GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
